module.exports = {
	LOGIN: 'Se Connecter',
	PASSWORD: 'Mot de passe',
	MIN_PASS: 'le mot de passe doit contenir au minimum 4 charactères',
	USERNAME: "Nom d'utilisateur",
	MIN_USERNAME: "le nom d'utilisateur doit contenir au minimum 4 charactères",
	WRONG_USERNAME: 'Le mot de passe entré est incorrect',
	LOGIN_HEADER: 'Bienvenu, Equipe Maison fondant',
	LOGIN_TITLE: 'Plateforme de gestion Team Maison Fondant',
	LOGIN_SUBTITLE: 'le 1ér réseau de réparateurs de confiance',
	REMINDER: 'Rappel',
	REMINDER_TITLE: 'Titre rappel',
	REMINDER_CONTENT: 'Description du rappel',
	REMINDER_SAVE: 'Enregistrer Rappel',
	REMINDER_UPDATE: 'Mettre a jour',
	CANCEL: 'Annuler',
	CODE: 'Code Suivi',
	PANNE: 'Panne',
	ETAT: 'état',
	PRICE: 'Prix',
	PROVIDER_PRICE: 'Prix Fournisseur',
	DEPOSIT_CENTER: 'Centre de dépot',
	REQUEST_DATE: 'Date Création',
	REPAIRER: 'Réparateur',
	REPARATION_CENTER: 'Centre de service',
	CLIENT: 'Client',
	DESCRIPTION: 'Déscription',
	AVANCE: 'Avance',
	RECUPERATION_CENTER: 'Centre de récuperation',
	ESTIMATED_TIME_REPARATION: 'Temps estimé pour réparation',
	ESTIMATED_TIME_DELIVERY: 'Temps estimé pour livraison',
};
